### PR TITLE
Tried to solve an error.

### PR DESCRIPTION
**Pull request by rexackermann**
When I used the script the app didn't run correctly ig.

>> fp <<app>>
Usage: <<app>>  [OPTIONS] COMMAND [ARGS]...
Try '<<app>> --help' for help.

Error: No such command ''.

### CODE REVIEW

**Comment by DLopezJr** [comment]
@RexAckermann 

Two things to check:

01. Did you change the permissions on the file to be executable?

You can do that like this:
```
$ chmod +x fp.sh
```

02. Are you in the same directory as the script when you launch the command? Unless you add the script to one of your $PATH directories you will have to be in the same path or you will have to type the entire path location for it out.

I will add a "Makefile" to automate those two steps.

To troubleshoot a bit more, enter this and then comment here the "Application ID" of the app you want to launch.
```
$ flatpak list --app
```

I can then make sure that the filtering is being done correctly. 

This is the output on my system.
```
$ flatpak list --app
Name       Application ID                 Version       Branch       Installation
Peek       com.uploadedlobster.peek       1.5.1         stable       system
VLC        org.videolan.VLC               3.0.18        stable       system
```

So on my system I can launch these two apps by typing this:
```
$ fp vlc
```
```
$ fp peek
```

**Comment by DLopezJr** [comment]
@RexAckermann 

I updated the repo with a "[Makefile](https://github.com/DLopezJr/fp/blob/main/Makefile)" and instructions in the "[README](https://github.com/DLopezJr/fp/blob/main/README.md)" on how to install/uninstall.

**Comment by rexackermann** [comment]
> @RexAckermann
> 
> Two things to check:
> 
> 1. Did you change the permissions on the file to be executable?
> 
> You can do that like this:
> 
> ```
> $ chmod +x fp.sh
> ```
> 
> 2. Are you in the same directory as the script when you launch the command? Unless you add the script to one of your $PATH directories you will have to be in the same path or you will have to type the entire path location for it out.
> 
> I will add a "Makefile" to automate those two steps.
> 
> To troubleshoot a bit more, enter this and then comment here the "Application ID" of the app you want to launch.
> 
> ```
> $ flatpak list --app
> ```
> 
> I can then make sure that the filtering is being done correctly.
> 
> This is the output on my system.
> 
> ```
> $ flatpak list --app
> Name       Application ID                 Version       Branch       Installation
> Peek       com.uploadedlobster.peek       1.5.1         stable       system
> VLC        org.videolan.VLC               3.0.18        stable       system
> ```
> 
> So on my system I can launch these two apps by typing this:
> 
> ```
> $ fp vlc
> ```
> 
> ```
> $ fp peek
> ```

Apparently vlc works but guiscrcpy didn't ,at least for me.

**Comment by DLopezJr** [comment]
@RexAckermann 

guiscrcpy works for me. Please send me the output of these two commands so I can try to help.

```
$ flatpak list --app
Name           Application ID         Version      Branch     Installation
guiscrcpy      in.srev.guiscrcpy      4.11.3       stable     system
```

```
$ fp guiscrcpy --help
Failed to load cairo: No module named 'cairosvg'
Some features are likely to be disabled
Usage: guiscrcpy [OPTIONS] COMMAND [ARGS]...

  guiscrcpy: Graphical user interface for scrcpy

Options:
  --version
  --license, --lic
  -T, --theme TEXT                Set the default theme (based on PyQt5 themes
                                  - Fusion, Breeze, Windows) (stored in
                                  configuration, override by --theme-no-cfg)
  -W, --hide-wm-frame / --show-wm-frame
                                  Show window manager border frame.
  --debug-disable-scrcpy          Do not launch scrcpy even when 'Start
                                  Scrcpy' is pressed
  -A, --always-on-top / --disable-always-on-top
                                  Forces the panels to be always of top
  --help                          Show this message and exit.

Commands:
  adb        Create an interface with the Android Debugging bridge
  config     View / Edit the configuration file
  fast-init  Init scrcpy before guiscrcpy
  mapper     Run the guiscrcpy mapper
  scrcpy     Create an interface with scrcpy

```

**Comment by rexackermann** [comment]
> @RexAckermann
> 
> guiscrcpy works for me. Please send me the output of these two commands so I can try to help.
> 
> ```
> $ flatpak list --app
> Name           Application ID         Version      Branch     Installation
> guiscrcpy      in.srev.guiscrcpy      4.11.3       stable     system
> ```
> 
> ```
> $ fp guiscrcpy --help
> Failed to load cairo: No module named 'cairosvg'
> Some features are likely to be disabled
> Usage: guiscrcpy [OPTIONS] COMMAND [ARGS]...
> 
>   guiscrcpy: Graphical user interface for scrcpy
> 
> Options:
>   --version
>   --license, --lic
>   -T, --theme TEXT                Set the default theme (based on PyQt5 themes
>                                   - Fusion, Breeze, Windows) (stored in
>                                   configuration, override by --theme-no-cfg)
>   -W, --hide-wm-frame / --show-wm-frame
>                                   Show window manager border frame.
>   --debug-disable-scrcpy          Do not launch scrcpy even when 'Start
>                                   Scrcpy' is pressed
>   -A, --always-on-top / --disable-always-on-top
>                                   Forces the panels to be always of top
>   --help                          Show this message and exit.
> 
> Commands:
>   adb        Create an interface with the Android Debugging bridge
>   config     View / Edit the configuration file
>   fast-init  Init scrcpy before guiscrcpy
>   mapper     Run the guiscrcpy mapper
>   scrcpy     Create an interface with scrcpy
> ```

These commands works but if i enter
`fp guiscrcpy`
I get


```./fp.sh guiscrcpy       
Failed to load cairo: No module named 'cairosvg'
Some features are likely to be disabled
Usage: guiscrcpy [OPTIONS] COMMAND [ARGS]...
Try 'guiscrcpy --help' for help.

Error: No such command ''.

>It should just launch the gui ,right ?
>Does it launch the gui for you ?

**Comment by DLopezJr** [comment]
@RexAckermann Thank you for the details! That was enough for me to debug it correctly.

Now when I do, ```fp guiscrcpy```, the GUI shows up. 

Please pull the repo and test with the new update and confirm that it works for you.

**Comment by rexackermann** [comment]
Thanks.

**Pull request closed without merging**
